name: R-CMD-check

on: [push, pull_request]

jobs:
  check:
    name: R CMD check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'  # Ajusta esto según la versión que necesites

      - name: Install dependencies
        run: |
          install.packages('devtools')
          devtools::install_deps()

      - name: Check
        run: |
          devtools::check()
