name: R CMD Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: R CMD Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4' # Specify the R version you want to use

    - name: Install dependencies
      run: |
        install.packages(c('devtools', 'roxygen2', 'testthat'), dependencies = TRUE)

    - name: Install package
      run: |
        devtools::install()

    - name: Run R CMD check
      run: |
        devtools::check()
